FROM openjdk:17

ARG DB_HOST
ARG DB_USER
ARG DB_PASSWORD
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_SECRET
ARG JWT_SECRET_KEY
ARG CLIENT_REDIRECT_URI
ARG BASE_URL

ENV DB_HOST=${DB_HOST} \
    DB_USER=${DB_USER} \
    DB_PASSWORD=${DB_PASSWORD} \
    KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID} \
    KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET} \
    JWT_SECRET_KEY=${JWT_SECRET_KEY} \
    CLIENT_REDIRECT_URI=${CLIENT_REDIRECT_URI} \
    BASE_URL=${BASE_URL}

ARG JAR_FILE=build/libs/*-SNAPSHOT.jar

COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
