package com.netflix.recommend.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Country {
    AFGHANISTAN("Afghanistan"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    ANGOLA("Angola"),
    ARGENTINA("Argentina"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    BAHAMAS("Bahamas"),
    BANGLADESH("Bangladesh"),
    BELGIUM("Belgium"),
    BERMUDA("Bermuda"),
    BRAZIL("Brazil"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    CAMBODIA("Cambodia"),
    CAMBODIA_("Cambodia,"),
    CAMEROON("Cameroon"),
    CANADA("Canada"),
    CAYMAN_ISLANDS("Cayman Islands"),
    CHILE("Chile"),
    CHINA("China"),
    COLOMBIA("Colombia"),
    CROATIA("Croatia"),
    CZECH_REPUBLIC("Czech Republic"),
    DENMARK("Denmark"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    EAST_GERMANY("East Germany"),
    ECUADOR("Ecuador"),
    EGYPT("Egypt"),
    ETHIOPIA("Ethiopia"),
    FINLAND("Finland"),
    FRANCE("France"),
    GEORGIA("Georgia"),
    GERMANY("Germany"),
    GHANA("Ghana"),
    GREECE("Greece"),
    GUATEMALA("Guatemala"),
    HONG_KONG("Hong Kong"),
    HUNGARY("Hungary"),
    ICELAND("Iceland"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAN("Iran"),
    IRAQ("Iraq"),
    IRELAND("Ireland"),
    ISRAEL("Israel"),
    ITALY("Italy"),
    JAMAICA("Jamaica"),
    JAPAN("Japan"),
    JORDAN("Jordan"),
    KENYA("Kenya"),
    KUWAIT("Kuwait"),
    LATVIA("Latvia"),
    LEBANON("Lebanon"),
    LIECHTENSTEIN("Liechtenstein"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALTA("Malta"),
    MAURITIUS("Mauritius"),
    MEXICO("Mexico"),
    MONTENEGRO("Montenegro"),
    MOROCCO("Morocco"),
    MOZAMBIQUE("Mozambique"),
    NAMIBIA("Namibia"),
    NEPAL("Nepal"),
    NETHERLANDS("Netherlands"),
    NEW_ZEALAND("New Zealand"),
    NICARAGUA("Nicaragua"),
    NIGERIA("Nigeria"),
    NORWAY("Norway"),
    PAKISTAN("Pakistan"),
    PANAMA("Panama"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    POLAND("Poland"),
    POLAND_("Poland,"),
    PORTUGAL("Portugal"),
    QATAR("Qatar"),
    ROMANIA("Romania"),
    RUSSIA("Russia"),
    SAUDI_ARABIA("Saudi Arabia"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SINGAPORE("Singapore"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOMALIA("Somalia"),
    SOUTH_AFRICA("South Africa"),
    SOUTH_KOREA("South Korea"),
    SOVIET_UNION("Soviet Union"),
    SPAIN("Spain"),
    SRI_LANKA("Sri Lanka"),
    SUDAN("Sudan"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    SYRIA("Syria"),
    TAIWAN("Taiwan"),
    THAILAND("Thailand"),
    TURKEY("Turkey"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    UNITED_KINGDOM("United Kingdom"),
    UNITED_KINGDOM_("United Kingdom,"),
    UNITED_STATES("United States"),
    URUGUAY("Uruguay"),
    VATICAN_CITY("Vatican City"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    WEST_GERMANY("West Germany"),
    ZIMBABWE("Zimbabwe");

    private final String name;
}
